### ISSUE TITLE
Plans for spigot/paperspigot improvements?

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#17]
Being a minetick fan for as long as i can remember i have not really messed with Spigot or PaperSpigot in a very long time.

However as you know i had to use them recently for testing purposes and wow config options!

There was so much crap to customize that ive never seen before that i was actually impressed, i was wondering if any of this stuff would be implemented into 1.7.10 minetick. From what i can see in the configs you can:
- Control baby zombie movement speed
- Async plugin bad magic catcher? No clue what this is.
- Limit player interactions
- Control the modifiers for potion effects
- Allow buckets to stack
- Keep spawn loaded
- Set max tick time
- Can signs stop falling blocks or not
- Maximum tick queue
- Async light updates
- Remove invalid spawners
- Squid spawn height
- Max growth height
- Minimum and Maximum fish time
- Player exhaustion
- Mob despawn range
- TNT entity height
- Complete generation control for canyons, caves, dungeons, fortresses, mineshafts, strongholds, temples, villages, and even flat bedrock o_O
- Allow enderpearls, tnt, or falling blocks to load chunks or not
- Optimize water and lava drain
- Control the speed of water and lava flow
- Make daylight detectors ACTUALLY WORK RIGHT! Holy crap someone actually did that!
- Cache size and cache limits
- Moved too quickly or wrongly threshold, this is nice since everyone who gets hit by a dragon floods the console with warnings.
- Control max life, speed, and damage
- Have dumb spawner mobs (Turn off the AI for mobs spawned from spawners)
- Dragon death sound radius, I wanted this in one of my plugins... But having it built into the server works too.
- Control the seed for features and villages
- Control player hunger
- Max TNT Entity control
- Enable pigmen portal spawning
- Hanging tick frequency
- Wither spawn sound radius
- Disable zombies attacking villagers

I think that's all of it. Anyways its quite the list and i dont think most of this stuff is even in minetick but it would be great if it did! Also a separate config file for minetick would also be nice.

Let me know whats going on, i always appreciate your work poweruser that's why ive been using minetick in any vanilla server environment Ive made on my network. I just want to see minetick be better known and can beat spigot in performance any day.

I was actually surprised 2 days ago i goofed and made some water 1 block higher then i needed and did /fixwater 50... Well that brought the server to its knees trying to calculate that for over 40 minutes >_>

And i think a bunch of that tick options above could have helped with that, especially limiting the amount of water flowing down into the void.

Also: This IS NOT asking you to implement their API i remember you saying you were not going to do that and thats fine. Im simply suggesting adding these into MineTick itself.

**Comment by Poweruser** [comment]
> I was actually surprised 2 days ago i goofed and made some water 1 block higher then i needed and did /fixwater 50...

Apart from the high radius and resulting long execution time of this worldedit command, running /fixwater 50 was actually a mistake. It raises the water level within the given range. So you flooded the area within a 100x100 square (50 in all directions). And the higher you were up in the air the worse it got, as the command also fills the air blocks below in this range with stationary water. Couple that with tons of event calls for flowing water, lightning updates and the fact that worldedit does all block changes in a single tick (unless you're running AsyncWorldEdit or something). I'm not at all surprised of the break down, that was predictable.

//pos1 & //pos2 on that height and //replace 8,9 0 would have done it. Also check the command `//limit <max operations>`, which limits the amount of block changes per worldedit command, quite useful for preventing lag spikes on larger repetivite changes

Concerning that list of improvements I'll reply later, if have to think this through first.

**Comment by Poweruser** [comment]
The first things that I'm going to do here are:
- a separate config file
- (internally) a separate config class for just managing the settings (currently everything is in the class MinetickMod among a bunch of other stuff)
- and a reload command

Then some comments on some of these settings

> Async plugin bad magic catcher? No clue what this is.

That is a precaution in Spigot against plugins that are doing some stuff on the server, they are only supposed to do from within the main thread / synchronous event handlers. And PaperSpigot added an option to disable it. It basically points out a design flaw in such plugins, and prevents that further damage can be done from that.
I had to check the accessing thread against the world ticking ones as well then.

> Async light updates

This one might be interesting and it would also fit into what I've already done

> Complete generation control for canyons, caves, dungeons, fortresses, mineshafts, strongholds, temples, villages, and even flat bedrock o_O

http://dev.bukkit.org/bukkit-plugins/terrain-control/ can do all this and much more.
Btw I'm thinking about removing the settings for the ore rates. They're not going to be reloadable without more ugly hacks

> Make daylight detectors ACTUALLY WORK RIGHT! Holy crap someone actually did that!

Can be archived with a some of redstone dust, one block and redstone torch as well.
Their "inverted" sensor is not exactly inverted: They calculate (15 - normal signal), but this as well: signal strengths below 10 turn the sensor off (no output) and strengths above 9 turn it on with full output. This is for a whole world. If someone wanted the normal behaviour back, their not going to get it.
I liked how [CraftBook](http://dev.bukkit.org/bukkit-plugins/craftbook/) does optional circuits. You mark it with a certain block and it behaves differently.

> Allow buckets to stack

No, not going to do that. What is a furnace supposed to do with 5 lava buckets in the fuel slot, when the first one is used up?

> Set max tick time

No, just think about yourself having fun with worldedit. How high would you set it, 40 minutes? :)
I'm actually surprised that they did that in 1.8, Mojang basically just copied what Spigot did up to that point.
I rather add an console emergency-shutdown command, which tells you what the main thread currently does, or maybe a dump of all important stack traces. And asks you then to confirm if you really want it

And the others, well I don't know. Some are useful in certain situations, some are meant to be done through plugins. And for me it doesn't feel right just to copy features of someone others work, just because it is there. A exception would be/are bugfixes.
