### ISSUE TITLE
How to use/install?

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#3]
I am currently using TickThreading on my modded servers.
(Not sure if this is for FORGE or not, looks like just plain ol bukkit)

How do i go about installing this on my server?
I want to install this on my spigot server (non modded) as tickthreading does not work for that.

**Comment by Poweruser** [comment]
As MinetickMod is a fork of CraftBukkit, everything is basically the same as it is there, except the internal changes.

Compiling:
Same as CraftBukkit. Get maven, clone the repo (or download and extract and source code), run 'mvn clean package' in the project folder. The compiled server jar is located in the .\target directory then

I've compiled and uploaded the server jars from the currently latest commits) for 1.7.2 and 1.7.9 here: [MinetickMod / Releases](https://github.com/Poweruser/MinetickMod/releases), if you cant get it compiled yourself

Installation:
Same as CraftBukkit. Copy the jar to your server directory and run it instead of whatever you are currently running. MinetickMod is not for Forge/MCPC/Minecraft with Mods, so don't try to run it inside such an already existing server setup.

Usage:
Same as CraftBukkit again. But MinetickMod brings along a few new commands and settings, which are explained in detail in the [Wiki](https://github.com/Poweruser/MinetickMod/wiki) of this repository

**Comment by Zilacon** [comment]
Thanks a lot for clearing this up because it was confusing the heck out of me lol.
I thought this was just another server wrapper like TT i had no idea it was the entire server jar itself.

Thanks!

**Comment by Zilacon** [comment]
Alright i got it loaded up.
It crashed on the first start when trying to load plugins up and get the metrics going.

The second time it started but the TPS and worldstats <world> command does not work.
Is this is a bug or is it not allowed to be ran on console?

**Comment by Poweruser** [comment]
- crash: may i have the error message and the stacktrace from the log please?
- commands: tps and worldstats weren't intended to be run from the console, both exit silently when the command sender is not a player (which the console is not), but I may add that

**Comment by Zilacon** [comment]
Cant give you a crash/error message it just deadlocked.

Froze for 15 mins no commands went through nothing i had to force close it.

**Comment by Poweruser** [comment]
In such a case you can get the stacktraces of all threads with the took 'jstack' from the JDK (if you have it installed), located in the ..\Programs\Java\jdk..\bin directory. Run it with 'jstack [ProcessID]'.  
And what version are you running? 1.7.2 or 1.7.9?

**Comment by Zilacon** [comment]
This is running on a live dedicated server with 5 other servers running on the same machine.
And its running on Linux Centos
And im using 1.7.9

**Comment by Poweruser** [comment]
@Zilacon Compiled a new version [1.7.9 Release r3](https://github.com/Poweruser/MinetickMod/releases/tag/1.7.9-R0.2_r3) with a bunch of important fixes

**Comment by Zilacon** [comment]
@Poweruser Thanks, ill throw this on my server.

That "slow chunk loading" is a bukkit and spigot problem too. Its like 1.7.9 loads chunks 1000x slower then previous versions. I figured it was mojang doing their genius programming again.

IMO Mojang needs to hire people like you to make their game and make a completely new version that relies more on performance and optimization then adding more broken crap into the game.

Have you tried 1.8? OH MY GOD... My graphics cards almost exploded from simply going to the menu on it. It is impossible to play on over 20 FPS.
And memory leaks! Holy memory leak! My client used up 2.9GB on 1.8 and i didnt have a single mod on it i was like wth is going on!?

It was so bad even MD_5 tweeted how horrible it was lol.

**Comment by Poweruser** [comment]
Two notes to the "slow chunk loading": 
- What I specifically meant in the changelog was a section of my own code that I had messed up myself, and not theirs.
  Thats the commit: https://github.com/Poweruser/MinetickMod/commit/cf463ca8083fed8e43c4d5a5dc56b34f2b606f11
  First I checked only the flag about chunk generation there. If those prohibited the generation of more chunks (to keep the server tick time low), the already existing chunks were then simply ignored. The more chunks were about to be generated the worse it got.
- In the client's video options (1.7.2 - 1.7.9, don't know about 1.8 there) you can set the fps limit. The lower that setting the faster the client will load the chunks. And the higher you set it, the slower the loading, as more cpu time is spent on rendering. Those two directly correlate with each other through the fps limit setting.
  If i set it to 20fps, the game and my test server on same PC (got a quad-core cpu) can easily keep up with loading when flying with speed 99 over a already generated area.

Edit: a 20fps limit (as example) is of course no option for enjoyable gaming. But try to find the balance around 40-60fps instead of setting anything ridiculous above 100
