### ISSUE TITLE
No chunks when flying.

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#7]
Loading chunks works perfectly fine when walking, or setting run speed to 10 and going sanic fast.

Start to fly? All chunk loading stops. It may load like 1-10 chunks in a 2 minute period if that. You land on the ground all chunks instantly start loading again.

Flying when the chunks aren't loading does not make the server error in any way, server runs at 20 tps with no lag or server delay. It simply does not load chunks when flying.

**Comment by Poweruser** [comment]
Don't have this issue in my test setup.
Code wise, the player height or the player being in flight mode is completely irrelevant to chunk loading. I don't remember having used any such check in there. Everything is done with the x and z coordinates.
I'll need more information about your test setup (related minetickmod settings, used plugins, ...)

**Comment by Zilacon** [comment]
Server: mc.apocgaming.org:8443

Plugins (43): WorldBorder, MultiWorld, CommandCooldown, LegendaryMessages, GroupManager, WorldEdit, DiabloDrops, ConsoleScheduler, mcore, Vault, LogBlock, VipSlot, uSkyBlock, WorldGuard, Reporter, MCBans, CommandsGuard, AntiAdvertising, QuickVote, LimitedCreative, GGTeleport, iDisguise, Resurrection, ChestShop, ProtocolLib, Identify, GriefPrevention, Votifier, mcMMO, PortableHorses, Essentials, StopThatLag, UltimateArena, AsyncWorldEdit, EssentialsSpawn, RegionForSale, TagAPI, TrashMotd, EnjinMinecraftPlugin, APOCPayday, EssentialsChat, Factions, NameTags

Configs are near default.

**Comment by Poweruser** [comment]
I might have a hunch on whats going wrong there. You said last night on teamspeak that the chunk loading while flying is not as slow anymore in the current version ( with includes this change: https://github.com/Poweruser/MinetickMod/commit/195960ad7ed05a9c5b6408d56d93b7e745ad6cf1 ), right? With that in mind, I can reproduce what you see, by artificially setting the flag `skipHeavyCalculations` to true.

**_What is `skipHeavyCalculations` and what does it do?_**
It is a boolean flag that is _false_ at the start of each server tick and is set to _true_ about 45 milliseconds after the start of each server tick. It's purpose is to notify the world threads that the server's maximum tick time (max 50ms in order to stay at 20tps) is almost reached and that they shall only do the absolute necessary work (and skip or delay the rest of it to later ticks) from now on until the end of the current server tick. The world threads regularly poll this flag before processing time consuming work, such as 
- ticking entities
- loading chunks (the case of this issue)
- generating chunks

In order for the `skipHeavyCalculations` flag to be set, there must be something on your server that causes a massive increase in cpu load once you are flying, which pushes the server tick time past the set 45ms barrier. Followed by a sudden drop once you are back on the ground. You should easily observe this with `top` or any other utility that monitors the cpu usage.
To get a more details, enable MinetickMod's profiler in it's settings (in bukkit.yml):

  `profiler-log-interval: 1`  (one log entry per second)
  `profiler-write-log: true`
  `profiler-write-interval: 1` (logs are written to disk every minute, so you dont have to wait so long)

and then fly/walk around (and switch a couple of times) on the server for a minute or two. The logs are written to the subdirectory `Profiler/year.month/day/` in the server's folder. Send me those files then. 
Check in the file that ends with `.._GameLogicLoop`, the column `Avg:`, which is the on average required time for a complete server tick. The column next to it holds the maximum tick time that was recorded.
