### ISSUE TITLE
Implement EVOC into MineTick?

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#8]
There is a mod available for forge clients/servers that tried to fix performance issues and help fix lag in certain areas. Its just 3 things in the mod so far but its being used in every updated technic modpack and ftb modpack.

http://www.mobiusstrip.eu/2013/12/05/evoc-1-0-0-mobiuscore-1-0-4/
Right now this is what it does:
- The hopper : Vanilla hoppers tend to hammer the server in one of those cases : Hopper is empty, hopper is completly full, no room in target inventory or source inventory empty. All those cases have been taken care of, providing a 10-folds reduction in update time for idle hoppers (from ~40µs down to ~4µs).
- The furnace : A furnace without carburant or internal heat but with a stack on top (typical idle furnace) was taking as long to update as a running furnace. That has been taken care of, and provides a 10-folds reduction in update time (from ~10µs to below ~1µs).
- The spawner : A fully lighted up spawner with a player around (classical below base spawner) could start hammering the server and reach a whooping ~300µs in update time. This value has been reduced to ~3µs by providing a delay in case there is no spot where the spawner can actually spawn things. This is a 100-folds decrease in update time.

I am not sure if anything like this has been done for MineTick but i figured id suggest it anyways.

**Comment by Poweruser** [comment]
So far I've just glanced over the changes, and looks like they're just little condition checks that shouldn't be too hard to add in ... once I get some other tasks done first.
I had already done an improvement on the hoppers:  https://github.com/Poweruser/MinetickMod/commit/64510ec75e55f17f38ff68ee0fc6947be1db55a1 which mainly addresses combinations of full hoppers and chests, where no moving is possible anymore

**Comment by Zilacon** [comment]
Alright cool.
Just trying to throw whatever i can think of your way to make minetick better :)

**Comment by Poweruser** [comment]
**Furnaces**: both branches had the checks for null already in them (in 1.7.2 added by CraftBukkit, in 1.7.9 by default). It did some adjustments though.  
In 1.7.2 the fuel slot is checked before the top slot, in order to skip the search for a recipe when there is no fuel. And in both I added a check for an empty bucket which can be left over from a previous cooking. I could have gone further and checked if an item in the fuel slot was a valid fuel at all, but that would break plugins that allow non-burning items as fuel, as no event would be called then anymore

**Comment by Poweruser** [comment]
Hoppers: now that's interesting, EVOC's hopper patch is already implemented identically in 1.7.9

**Comment by Poweruser** [comment]
**Spawners**: EVOC's spawner patch is not in 1.7.9, but I can emphasize why Mojang did not copy it as well:  
If spawning failed, every possible spawn location (within the spawn range in a 3d grid with 1m spacing) is checked, if a entity can spawn there, which is ... _meh_, until one is found. If none is found, the spawningDelay is set to 20, in order to skip spawning attempts for one second.  
I am as well, not going to add this. Instead I'll do this:  
There'll be a new variable `spawningPenalty` for each spawner that starts off at 0. Everytime `spawnDelay` is reset, it is set back to 0. And everytime a spawn attempt failed, it is increased by one, up to a cap limit of 40 (I'll go with 2 seconds, instead of 1), and added to `spawnDelay`. Successive failed attempts are throttled this way, until spawning succeeds. And the delay game starts over.

And I found some dead code:
https://github.com/Poweruser/MinetickMod/blob/74e2a9a9ae58f8ee94ebeecbebb8e2849cbb85ba/src/main/java/net/minecraft/server/MobSpawnerAbstract.java#L67
`spawnDelay` can never reach -1 because of:
https://github.com/Poweruser/MinetickMod/blob/74e2a9a9ae58f8ee94ebeecbebb8e2849cbb85ba/src/main/java/net/minecraft/server/MobSpawnerAbstract.java#L70

**Comment by Zilacon** [comment]
Cool, thanks for checking it out.
